# Generated by Django 4.2 on 2023-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='./media/HomeCustom/logo/img/%y/%m/%d/')),
                ('title', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=5024)),
            ],
            options={
                'verbose_name': 'HomeCustom',
                'verbose_name_plural': 'HomeCustoms',
            },
        ),
    ]
